### ISSUE TITLE
network_numRequests 值获取有小数

### ISSUE THREAD

**Issue by oslet** [ZhuoRoger/mongomon#1]
PROBLEM
P3
Endpoint:Db-38-MongoDb-2
Metric:network_numRequests
Tags:mongo=10001
all(#3): 603.73333>500
Note:当前收到的总请求数每秒超过500
Max:3, Current:1
Timestamp:2016-06-17 14:53:00

使用此插件得到的数值有小数，这是个 Bug ?

**Comment by ZhuoRoger** [comment]
不是bug.  指标是"counterType": "COUNTER"类型的；每1分钟，上报一次数据，会计算为每秒多少个。因为在mongodb db.serverStatus()是累计值 。
